title: Vision Waves
description: > # this means to ignore newlines until "baseurl:"
 Data is power!
baseurl: ""
url: ""
permalink: /:year/:month/:day/:title
#repository: 
paginate: 5
paginate_path: "/blog/:num/" #ez lehet baj lesz

# MatJek specific configurations
github_profile: "https://github.com/tamarci"
linkedin_profile: "https://www.linkedin.com/in/márton-tárnok-4134451a4/"
user: "Marton Tarnok"
user_email: "email_kukac_gmail.com"
contact_url: "https://goo.gl/tVljbV"
google_tracking_id: "UA-96359860-1"
google_site_verification: "UA-96359860-1"
disqus_shortname: "Marton"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true